### PR TITLE
提交平方和

### LINKED ISSUE #3919: [Program]: Write a R program to find sum of squares of numbers
### Description

Write a R program to find sum of squares of numbers

Suppose you have a list of numbers, and you want to find the sum of the squares of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the squares of those numbers, which is `1^2 + 2^2 + 3^2 = 14`.

```
Input  : 1 2 3 4 5
Output : 55
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-sum-of-squares-of-numbers/find_sum_of_squares_of_numbers.r` file

</details>

### PR DESCRIPTION
**Pull request by lululululu0907**
## 📑 Description

copilot:summary

## 🐞 Related Issue

Closes #3919

## 📋 Explanation of changes

copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
Can you please add the issue id to this PR

**Review by anandfresh — CHANGES_REQUESTED** [review]
Can you please code only in English ?

**Comment by lululululu0907** [comment]
> 你能只用英文编码吗？

ok

**Comment by lululululu0907** [comment]
> 您能否将问题 ID 添加到此 PR 中

i dont know how to do

**Review by harshraj8843 — APPROVED** [review]
> 感谢您的贡献🤗

Thanks for contributing 🤗

**Review by RiteshK-611 — APPROVED** [review]

**Review by anandfresh — APPROVED** [review]

**Pull request merged**
