### PR TITLE
[Closed] octal to decimal

### LINKED ISSUE #513: [Program]: Write a Ruby program to convert octal to decimal
### Description

Write a Ruby program to convert octal to decimal

Octal is a base-8 number system. It uses only eight digits: 0, 1, 2, 3, 4, 5, 6, and 7. The digits are called octits. An octit is the smallest unit of information in a computer. An octit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, or 7, or it can be used to represent a single state, such as on or off.

To convert an octal number to decimal, we can use the following algorithm:

1. Multiply the first octit by 8^0.
2. Multiply the second octit by 8^1.
3. Multiply the third octit by 8^2.
4. Multiply the fourth octit by 8^3.
5. Repeat steps 3 and 4 until the last octit.
6. Add the results of all the multiplications.
7. The decimal number is the sum of all the multiplications.

```
Input  : 12
Output : 10
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-octal-to-decimal/ConvertOctalToDecimal.rb` file

</details>

### PR DESCRIPTION
**Pull request by maheshmeleti**
## 🐞 Related Issue

Closes #513

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
@maheshmeleti please add the issue id to this PR

**Comment by maheshmeleti** [comment]
made the required changes, kindly look into it.

**Review by anandfresh — CHANGES_REQUESTED** [review]
@maheshmeleti Can you please add an example to execute this function by giving an input as shown in the issue.

**Review by anandfresh — CHANGES_REQUESTED** [review]
@maheshmeleti Can you please add an example to execute this function by giving an input as shown in the issue.

**Comment by isyuricunha** [comment]
This PR will be closed, and it can be reopened if the author requests it and/or wishes to do so.

Clarification:

A change was requested in the PR, but the author did not make the modifications needed for the merge to be authorized.

**Pull request closed without merging**
