### PR TITLE
C# Convert Decimal to Hexadecimal

### LINKED ISSUE #2869: [Program]: Write a C# program to convert decimal to hexadecimal
### Description

Write a C# program to convert decimal to hexadecimal

Hexadecimal is a base-16 number system. It uses sixteen digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, and F. The digits are called hexits. A hexit is the smallest unit of information in a computer. A hexit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, or F, or it can be used to represent a single state, such as on or off.

To convert a decimal number to hexadecimal, we can use the following algorithm:

1. Divide the decimal number by 16.
2. Write down the remainder.
3. Divide the quotient by 16.
4. Write down the remainder.
5. Repeat steps 3 and 4 until the quotient is 0.
6. The hexadecimal number is the sequence of remainders written in reverse order.

```
Input  : 10
Output : A
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-decimal-to-hexadecimal/program/ConvertDecimalToHexadecimal.cs` file

</details>

### PR DESCRIPTION
**Pull request by LinoyYarkoni**
## 📑 Description

copilot:summary

## 🐞 Related Issue

Closes #2869

## 📋 Explanation of changes

copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
@LinoyYarkoni  can you please invoke this class with an input as shown in the issue id : #2869

**Comment by LinoyYarkoni** [comment]
> @LinoyYarkoni can you please invoke this class with an input as shown in the issue id : #2869

image

Is this OK?
Thanks

**Comment by anandfresh** [comment]
> > @LinoyYarkoni can you please invoke this class with an input as shown in the issue id : #2869
> 
> image
> 
> Is this OK? Thanks

@LinoyYarkoni can you give an input value and invoke

**Comment by LinoyYarkoni** [comment]
I noticed that I need to reverse the result.
I will open a new pull request soon.

**Comment by LinoyYarkoni** [comment]
Do I have to do anything else?

**Review by anandfresh — APPROVED** [review]

**Review by 0ME9A — CHANGES_REQUESTED** [review]
I think there is some issue/error in the program.
@LinoyYarkoni , @anandfresh 
Error:-
```
main.cs(3,64): error CS1525: Unexpected symbol `)', expecting `(' or `type'
main.cs(5,15): error CS1519: Unexpected symbol `0' in class, struct, or interface member declaration
main.cs(5,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(6,9): error CS9010: Primary constructor body is not allowed
main.cs(6,10): error CS1525: Unexpected symbol `,', expecting `(' or `type'
main.cs(6,16): error CS1002: ; expected
main.cs(6,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(7,9): error CS9010: Primary constructor body is not allowed
main.cs(7,10): error CS1525: Unexpected symbol `,'
main.cs(7,16): error CS1002: ; expected
main.cs(7,9): error CS8041: Primary constructor already has a body
main.cs(7,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(8,9): error CS9010: Primary constructor body is not allowed
main.cs(8,10): error CS1525: Unexpected symbol `,'
main.cs(8,16): error CS1002: ; expected
main.cs(8,9): error CS8041: Primary constructor already has a body
main.cs(8,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(9,9): error CS9010: Primary constructor body is not allowed
main.cs(9,10): error CS1525: Unexpected symbol `,'
main.cs(9,16): error CS1002: ; expected
main.cs(9,9): error CS8041: Primary constructor already has a body
main.cs(9,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(10,9): error CS9010: Primary constructor body is not allowed
main.cs(10,10): error CS1525: Unexpected symbol `,'
main.cs(10,16): error CS1002: ; expected
main.cs(10,9): error CS8041: Primary constructor already has a body
main.cs(10,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(11,9): error CS9010: Primary constructor body is not allowed
main.cs(11,10): error CS1525: Unexpected symbol `,'
main.cs(11,16): error CS1002: ; expected
main.cs(11,9): error CS8041: Primary constructor already has a body
main.cs(11,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(12,9): error CS9010: Primary constructor body is not allowed
main.cs(12,10): error CS1525: Unexpected symbol `,'
main.cs(12,16): error CS1002: ; expected
main.cs(12,9): error CS8041: Primary constructor already has a body
main.cs(12,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(13,9): error CS9010: Primary constructor body is not allowed
main.cs(13,10): error CS1525: Unexpected symbol `,'
main.cs(13,16): error CS1002: ; expected
main.cs(13,9): error CS8041: Primary constructor already has a body
main.cs(13,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(14,9): error CS9010: Primary constructor body is not allowed
main.cs(14,10): error CS1525: Unexpected symbol `,'
main.cs(14,16): error CS1002: ; expected
main.cs(14,9): error CS8041: Primary constructor already has a body
main.cs(14,17): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(15,9): error CS9010: Primary constructor body is not allowed
main.cs(15,11): error CS1525: Unexpected symbol `,'
main.cs(15,17): error CS1002: ; expected
main.cs(15,9): error CS8041: Primary constructor already has a body
main.cs(15,18): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(16,9): error CS9010: Primary constructor body is not allowed
main.cs(16,11): error CS1525: Unexpected symbol `,'
main.cs(16,17): error CS1002: ; expected
main.cs(16,9): error CS8041: Primary constructor already has a body
main.cs(16,18): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(17,9): error CS9010: Primary constructor body is not allowed
main.cs(17,11): error CS1525: Unexpected symbol `,'
main.cs(17,17): error CS1002: ; expected
main.cs(17,9): error CS8041: Primary constructor already has a body
main.cs(17,18): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(18,9): error CS9010: Primary constructor body is not allowed
main.cs(18,11): error CS1525: Unexpected symbol `,'
main.cs(18,17): error CS1002: ; expected
main.cs(18,9): error CS8041: Primary constructor already has a body
main.cs(18,18): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(19,9): error CS9010: Primary constructor body is not allowed
main.cs(19,11): error CS1525: Unexpected symbol `,'
main.cs(19,17): error CS1002: ; expected
main.cs(19,9): error CS8041: Primary constructor already has a body
main.cs(19,18): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
main.cs(20,9): error CS9010: Primary constructor body is not allowed
main.cs(20,11): error CS1525: Unexpected symbol `,'
main.cs(20,17): error CS1002: ; expected
main.cs(20,9): error CS8041: Primary constructor already has a body
main.cs(23,18): error CS1525: Unexpected symbol `void', expecting `class', `delegate', `enum', `interface', `partial', `ref', or `struct'
Compilation failed: 77 error(s), 0 warnings
```

**Review by 0ME9A — APPROVED** [review]
The code successfully run✨

**Pull request merged**
