### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by harshraj8843**
## 📑 Description

- Update README

### CODE REVIEW

**Comment by isyuricunha** [comment]
Hey @harshraj8843 , do you need me to proofread the readme in other languages?

**Comment by harshraj8843** [comment]
Your expertise will be of great help! :)

**Comment by harshraj8843** [comment]
@isyuricunha Should we create `good first issues` for README translations in other languages as well 🤔 ?

**Comment by isyuricunha** [comment]
> @isyuricunha Should we create `good first issues` for README translations in other languages as well 🤔 ?

It would be a good idea for other people to contribute as well. But it might take a long time to complete.

At the moment I can review what we have and what is being changed, and I can also add two or three more languages (then I'd run out of all the languages I know).

**Pull request merged**
