### PR TITLE
New feature to convert date from standard format to julian and vice-versa

### LINKED ISSUE #5475: Write a Python program to convert standard date format to julian date and vice-versa
### Description

Write a Python program to convert standard date format to julian date and vice-versa

A Julian date is a way of displaying a date that combines the current year with the number of days since the beginning of the year. For example, January 1, 2007 is 2007001, and December 31, 2007 is 2007365.

The first two digits of a Julian date represent the year, and the last three digits represent the number of days since the beginning of the year. For example, 21-001 represents January 1, 2021, and 22-165 represents June 14, 2022.

### Example

```
Input  : 2023-06-10
Output : 2023160
```

<sub>Contributed by - @magar51</sub>
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/convert-standard-date-format-to-julian-date-and-vice-versa/convert_standard_date_format_to_julian_date_and_vice-versa.py`
- Commit the changes
- Create a pull request

</details>

### PR DESCRIPTION
**Pull request by magar51**
## 🐞 Related Issue

Closes #5475

### CODE REVIEW

**Review by isyuricunha — APPROVED** [review]

**Comment by harshraj8843** [comment]
Hey @magar51 

Thanks for this program.

We are working on our program GitHub Action which will help us create issues for this program in multiple languages.

Till then please wait for this PR to be merged. Thanks 🤗

**Review by anandfresh — CHANGES_REQUESTED** [review]
@magar51 Please add the issue id to this PR

**Comment by magar51** [comment]
New issue created:  Date Converter #5402
Please have a look

**Comment by isyuricunha** [comment]
> New issue created: Date Converter #5402 Please have a look



> New issue created: Date Converter #5402 Please have a look

Hi,

You need to include the ID of the solution you started working on. In this case, you created #5402, right? So you need to put its ID in the body of the PR. For example:

```
Related Issue:

Closes #5402
```

Do you understand?

I will add the ID this time, but please remember to do it next time. With that said, let's wait for @harshraj8843 and @anandfresh to take another look at this PR and the issue.

**Review by anandfresh — APPROVED** [review]

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
