### PR TITLE
Find Smallest ElementIn a Matrix

### LINKED ISSUE #3794: [Program]: Write a Ruby program to find smallest element in a matrix
### Description

Write a Ruby program to find smallest element in a matrix

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

<sub>Contributed by - @ShubhraSuman</sub>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-smallest-element-in-a-matrix/FindSmallestElementInAMatrix.rb` file

</details>

### PR DESCRIPTION
**Pull request by anandfresh**
## 📑 Description

copilot:summary

## 🐞 Related Issue

Closes #3794

## 📋 Explanation of changes

copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by 0ME9A — APPROVED** [review]
The code is concise and achieves the desired result of finding the smallest element in the matrix.

**Review by hi-Kartik2004 — APPROVED** [review]

**Comment by 0ME9A** [comment]
hello, @harshraj8843 can you check out this?

**Review by harshraj8843 — APPROVED** [review]
😍

**Comment by harshraj8843** [comment]
> hello, @harshraj8843 can you check out this?

There is some issue with the vercel preview, it gets triggered even if the `apps` files are not changed.

I am already using `npx turbo-ignore` as mentioned here 👉🏻 https://turbo.build/repo/docs/core-concepts/monorepos/skipping-tasks#using-turbo-ignore-on-vercel, but it doesn't seem to be working

I will try to fix this issue as soon as possible.

**Pull request merged**
