### PR TITLE
Convert decimal to octal

### LINKED ISSUE #790: [Program]: Write a Perl program to convert decimal to octal
### Description

Write a Perl program to convert decimal to octal

Octal is a base-8 number system. It uses only eight digits: 0, 1, 2, 3, 4, 5, 6, and 7. The digits are called octits. An octit is the smallest unit of information in a computer. An octit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, or 7, or it can be used to represent a single state, such as on or off.

To convert a decimal number to octal, we can use the following algorithm:

1. Divide the decimal number by 8.
2. Write down the remainder.
3. Divide the quotient by 8.
4. Write down the remainder.
5. Repeat steps 3 and 4 until the quotient is 0.
6. The octal number is the sequence of remainders written in reverse order.

```
Input  : 10
Output : 12
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-decimal-to-octal/convert_decimal_to_octal.pl` file

</details>

### PR DESCRIPTION
**Pull request by anandfresh**
## 📑 Description

copilot:summary

## 🐞 Related Issue

Closes #790

## 📋 Explanation of changes

copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by hi-Kartik2004 — APPROVED** [review]

**Review by 0ME9A — CHANGES_REQUESTED** [review]
Hey @anandfresh,
I think there is a problem with your code logic. 🧑‍💻
The Octal of 10 must be 12, not 8.

image

**Review by hi-Kartik2004 — APPROVED** [review]
Hi @anandfresh,
I have fixed the issue with this `script and it works perfectly`, @0ME9A could you verify the same?😃

**Review by 0ME9A — APPROVED** [review]
Hi @hi-Kartik2004,

Thank you for reviewing the program and making the necessary fixes. However, I have noticed a small issue that needs to be addressed. The program currently does not handle negative numbers. Although it's not a major problem, it can be easily fixed with just one line of code. 🧑‍💻

image

**Comment by hi-Kartik2004** [comment]
Hi @0ME9A,
Thanks for highlighting the missed case, the code is updated and works for negative numbers.

**Review by 0ME9A — COMMENTED** [review]
Perfecto👌

**Pull request merged**
