### PR TITLE
R program to convert string to vowelcase added

### LINKED ISSUE #3603: [Program]: Write a R program to convert string to vowelcase
### Description

Write an R function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "R Language"
    Output: "r lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_vowelcase.r` file
- Add `convert_string_to_vowelcase.r` file in `convert-string-to-vowelcase` folder

</details>

### PR DESCRIPTION
**Pull request by namrata18s**
## 📑 Description

copilot:summary
R program to convert string to vowelcase

## 🐞 Related Issue

Closes #3603

## 📋 Explanation of changes

copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by 0ME9A — COMMENTED** [review]
Hi @namrata18s,

I noticed that the `convertToVowelcase` function is not correctly converting uppercase vowels to vowelcase. The current code is only checking if a character is equal to any of the vowels "a", "e", "i", "o", or "u". This means that if a character is uppercase, it will not be recognized as a vowel.

#### Program Prints
Input : Programming IS Fun 
Output : prOgrAmmIng is fUn 
_Expected: prOgrAmmIng Is fUn_

To fix this issue, you need to modify the `isVowel` function to convert the character to lowercase before checking if it's a vowel. This will ensure that both uppercase and lowercase vowels are correctly converted to vowelcase.

Here's the code you can update:

```R
isVowel <- function(char) {
  vowels <- c("a", "e", "i", "o", "u")
  char <- tolower(char)  # Convert character to lowercase
  return(char %in% vowels)
}
```

Please update your code and let me know if you have any questions.

**Comment by namrata18s** [comment]
Hi @0ME9A ,
Thanks for pointing out the issue in the convertToVowelcase function. To address the problem, I have modified the isVowel function as suggested. Could you please review it from your side? Thankyou

**Review by 0ME9A — APPROVED** [review]
@namrata18s,

Thanks for taking the time to updating the code. Your contribution is much appreciated!

**Comment by namrata18s** [comment]
Could you please merge the PR to close this issue? Thankyou

**Comment by 0ME9A** [comment]
Hey @namrata18s,

I appreciate your eagerness to get this issue resolved. I've reviewed the code and found it to be well-structured and functioning properly. While I'm confident in merging it, our policy requires a minimum of two reviewers for pull request merges. This helps ensure the quality and maintainability of our codebase.

I'll encourage additional reviewers to provide their feedback promptly, and we'll proceed with merging the pull request once the required approvals are in place. Thank you for your understanding and cooperation.

**Review by victoriacheng15 — APPROVED** [review]
The code is well-written and clear. Thank you for your contribution!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
