### PR TITLE
New Website UI

### PR DESCRIPTION
**Pull request by harshraj8843**
## 📑 Description

- New website UI using [daisyui](https://daisyui.com/)
- Christmas Special

Demo 👉🏻 https://codinasion-git-web-beta-codinasion.vercel.app

### CODE REVIEW

**Comment by harshraj8843** [comment]
| Dark Theme | Light Theme |
|---|---|
| Screenshot from 2023-12-21 17-18-13 | Screenshot from 2023-12-21 17-32-41 |

**Comment by harshraj8843** [comment]
Feedback or suggestions will be helpful

**Comment by 0ME9A** [comment]
Hi @harshraj8843,

Thanks for your request! I've taken a look at the current design of the Codinasion website, and while it's functional, I've noticed a few areas where improvements could enhance its overall appeal.

Aesthetic Issues:

- The design lacks visual appeal, and there are inconsistencies in the layout that could be addressed.

Christmas Theme Proposal:

- Given the proximity to Christmas, I'd like to propose a festive Christmas theme to add a touch of holiday spirit. This could involve incorporating seasonal colours, subtle snow effects, and thematic graphics.

Timing Constraints:

- Considering the upcoming holiday in just 2 days and my current schedule, extensive improvements might not be feasible. However, I'm happy to assist post-Christmas if a more thorough revamp is desired.

Feel free to review the suggestions, and let me know if you'd like to proceed with the Christmas theme or discuss further improvements in the new year. Thanks!

Best,
@0ME9A

**Comment by harshraj8843** [comment]
Thanks, @0ME9A, for your review. I agree with all the points you made. However, we won't be able to fix it right away due to time constraints. We'll work on it after the New Year. 🎉 🤗

**Comment by isyuricunha** [comment]
Hey folks, @harshraj8843 & @0ME9A,

So, personally, I didn't feel the need to comment on what was done; there were no thoughts in my mind that would be to enhance or improve anything, so I refrained from commenting.

Currently, from what I see, it was a great job, especially considering that we are one or two days away from Christmas and its celebratory festivities.

Speaking about the design coming up for next year, I'll be here to help with its programming if needed.

P.S.: As I mentioned in a previous comment, I'm not very good at drawing and/or imagining design.

Cheers,
Yuri.

**Comment by harshraj8843** [comment]
Thanks @isyuricunha @0ME9A 🤗

**Pull request merged**
