### PR TITLE
convert_time_from_24-hour_to_12-hour_format rust program

### LINKED ISSUE #3220: [Program]: Write a Rust program to convert time from 24-hour to 12-hour format
### Description

Write a Rust program that takes a string representing a time in 24-hour format (HH:MM:SS) and converts it to 12-hour format (HH:MM:SSAM/PM). The program should handle invalid inputs and edge cases gracefully.

### Examples/Test Cases:

- **Example 1:**
  - Input: `"12:05:45"`
  - Output: `"12:05:45PM"`
  - Description: The program should accurately convert a valid 24-hour time to the 12-hour format.

- **Example 2:**
  - Input: `"00:15:30"`
  - Output: `"12:15:30AM"`
  - Description: The program should handle midnight correctly and display "AM" appropriately.

- **Example 3:**
  - Input: `"18:45:12"`
  - Output: `"06:45:12PM"`
  - Description: The program should convert an evening time to the 12-hour format.

- **Example 4:**
  - Input: `"25:10:05"`
  - Output: `"Invalid input"`
  - Description: The program should detect an invalid hour and display an error message.

- **Example 5:**
  - Input: `"09:60:00"`
  - Output: `"Invalid input"`
  - Description: The program should detect an invalid minute and display an error message.

- **Example 6:**
  - Input: `"abc"`
  - Output: `"Invalid input"`
  - Description: The program should handle non-numeric inputs and display an error message.

Contributors attempting to address this issue should focus on implementing these functionalities and thoroughly testing the program with these test cases.

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-time-from-24-hour-to-12-hour-format/program/convert_time_from_24-hour_to_12-hour_format.rs` file

</details>
            

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-time-from-24-hour-to-12-hour-format/program/convert_time_from_24-hour_to_12-hour_format.rs` file

</details>

### PR DESCRIPTION
**Pull request by SaideepKondur**
## 📑 Description
I've added a Rust program that converts time from 24-hour to 12-hour format. The user is prompted to input the time in the 24-hour format (HH:MM:SS), and the program outputs the time in the 12-hour format, including AM or PM.

Here's an example of the conversion:

Input: 12:05:45
Output: 12:05:45PM

The solution utilizes standard input/output for user interaction and performs the conversion logic in Rust.

## 🐞 Related Issue

Closes #3220

### CODE REVIEW

**Comment by SaideepKondur** [comment]
@harshraj8843 It is asking for vercel authorization to approve. Could you kindly look into it and provide me with any leads to approve the merge

**Review by 0ME9A — COMMENTED** [review]
Enhance time conversion and add input validation

@SaideepKondur, the current implementation of the time conversion program is almost correct, such as the accurate conversion of valid 24-hour input to the 12-hour format. However, there are a couple of areas where input validation is lacking.

Positive Aspects:
- Accurate conversion of valid 24-hour input to 12-hour format.
- Proper determination of AM or PM.

The program should validate:
- Validate that the parsed hour is between 0 and 23.
- Validate that the parsed minute is between 0 and 59.
- Validate that the parsed second is between 0 and 59.

This ensures that only valid 24-hour time formats are accepted, preventing errors like "10203:123:3232" from being processed.



@SaideepKondur, please review and update the required changes. Feel free to reach out if you have any questions or if further adjustments are needed.

Screenshot 2023-11-30 104036

**Review by SaideepKondur — COMMENTED** [review]
validated hours, minutes and seconds format in Rust program to convert time from 24-hour to 12-hour format

**Comment by SaideepKondur** [comment]
@0ME9A I have validated hours, minutes and seconds format in Rust program to convert time from 24-hour to 12-hour format. I have changed the previous file. Kindly have a look and let me know if any changes are required. Do consider merging it. Thank you

**Review by 0ME9A — APPROVED** [review]
Hats off to @SaideepKondur for an exceptional job on resolving Issue #3220! 🎉 I'm truly impressed with the code quality and the effective solution provided. Your attention to detail and commitment to excellence shine through. 👏 This is a significant contribution that greatly enhances our project.

Thanks a million for your dedication and hard work!

Best,
@0ME9A

**Comment by SaideepKondur** [comment]
Thanks a lot @0ME9A. @grraghav120 kindly approve the merge since merging requires 2 approving reviews. And also Vercel is asking for authorization.

**Comment by 0ME9A** [comment]
Happy 😊

**Comment by SaideepKondur** [comment]
@0ME9A Yes!!!, Thanks a lot 😊

**Pull request merged**
