### PR TITLE
String to Sentencecase

### LINKED ISSUE #3726: [Program]: Write a Perl program to convert string to sentencecase
### Description

Write a Perl program that converts a string to a sentence case.

Sentence case is a style of writing in which the first letter of the first word is capitalized, while all other letters are in lowercase. However, there are some exceptions to this rule. For example, proper nouns (such as names of people, places, organizations, etc.) and acronyms (such as NASA, FBI, etc.) should always be capitalized, regardless of their position in the sentence. The first word after a colon or a semicolon may also be capitalized.

Here is an example of a sentence in sentence case: "**The quick brown fox jumps over the lazy dog.**" In this sentence, only the first letter of the first word is capitalized, while all other letters are in lowercase. However, if the sentence contains proper nouns or acronyms, they should also be capitalized. For example: "**John and Jane went to New York to visit the Museum of Modern Art (MoMA).**" In this sentence, the first letter of the first word, as well as the proper nouns "John", "Jane", "New York", and "Museum of Modern Art", and the acronym "MoMA" are capitalized.

Here are some examples of converting strings to sentence case using a Perl program:

Example 1:
```
Input: "john and jane went to new york to visit the museum of modern art (moma)"
Output: "John and Jane went to New York to visit the Museum of Modern Art (MoMA)"
```

Example 2:
```
Input: "the united nations (un) is an international organization"
Output: "The United Nations (UN) is an international organization"
```

Example 3:
```
Input: "the cat is sleeping; however, the dog is awake"
Output: "The cat is sleeping; however, the dog is awake"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-sentencecase/convert_string_to_sentencecase.pl` file

</details>

### PR DESCRIPTION
**Pull request by anandfresh**
## 📑 Description

copilot:summary

## 🐞 Related Issue

Closes #3726

## 📋 Explanation of changes

copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by victoriacheng15 — APPROVED** [review]
Thank you for your contribution!

**Review by 0ME9A — COMMENTED** [review]
The code doesn't convert text into sentence cases, it just follows the documentation.

Input:- "this is Just a Dummy teXt. tryTo corRect it."
Output:- "This is Just a Dummy teXt. tryTo corRect it."
Output expected:- "This is just a dummy text. Try to correct it."

**Comment by anandfresh** [comment]
> The code doesn't convert text into sentence cases, it just follows the documentation.
> 
> Input:- "this is Just a Dummy teXt. tryTo corRect it." Output:- "This is Just a Dummy teXt. tryTo corRect it." Output expected:- "This is just a dummy text. Try to correct it."

@0ME9A , the issue has been fixed. Kindly retest.

**Comment by 0ME9A** [comment]
Hey @anandfresh, I've updated the documentation, Please read the new doc https://github.com/codinasion/codinasion/issues/3726

**Review by 0ME9A — COMMENTED** [review]
Please read the new doc. https://github.com/codinasion/codinasion/issues/3726

**Review by 0ME9A — APPROVED** [review]

**Pull request merged**
