### PR TITLE
created PrintAsciiValueOfAString.cs

### LINKED ISSUE #480: [Program]: Write a C# program to print ascii value of a string
### Description

Write a C# program to print ascii value of a string

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : ABC
Output : 65 66 67
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-ascii-value-of-a-string/PrintAsciiValueOfAString.cs` file

</details>

### PR DESCRIPTION
**Pull request by g-s-eire**
## 📑 Description

- Added PrintAsciiValueOfAString.cs file in print-ascii-value-of-a-string folder.
- Created the C# program to print string user input ASCII values.

Type of change:
    New feature (non-breaking change which adds functionality)

What is the solution?
    The solution is a C# application that takes a user input from the input stream, and with its value calls a method that iterates 
    through all characters and converts them into an integer; then this is printed to the screen.

Closes #480

---

copilot:all

### CODE REVIEW

**Comment by g-s-eire** [comment]
Hi this issue was originally #580, and was assigned to me. Recently that was archived. 
image

**Comment by harshraj8843** [comment]
Hey @g-s-eire 

Please `Allow edits from maintainers`

Reference: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by g-s-eire** [comment]
Hi @harshraj8843 , I created the pull request from an organization owned fork, and it seems only personally owned forks can allow maintainers to edit. GitHub Issue reference: https://github.com/orgs/community/discussions/5634
Please advise, how to proceed.

**Comment by harshraj8843** [comment]
Hey @g-s-eire, in this case, please update the code as below (to resolve the `Error: 'System.Console' does not contain a definition for 'Readline'`

```cs
using System;

namespace CSharpStringToASCII {
    public class PrintAsciiValueOfAString {
        // method to convert string and prints ASCII values
        public static void PrintAsciiValues(string userInput) {
            // error handling for invalid inputs
            try{
                // iterating through user input
                foreach(char c in userInput){
                    // converting char to int
                    int asciiValue = (int)c;
                    // printing relevant char and its ASCII value
                    Console.WriteLine($"Char: {c}, ASCII value: {asciiValue}");
                }
            }
            catch{
                Console.WriteLine("Invalid input");
            }         
        }
        // main method
        public static void Main(string[] args) {
            // prompting user for input
            Console.Write("Enter a string: ");
            // read user input from input stream
            string userInput = Console.ReadLine();
            // calling method to print ASCII values of the input
            PrintAsciiValues(userInput);
        }
    }
}
```

**Comment by g-s-eire** [comment]
Hi @harshraj8843 , The suggested changes have been implemented. Please let me know if any additional changes needed. Thanks.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
