### PR TITLE
Create convert_string_to_sentencecase.dart

### LINKED ISSUE #3718: [Program]: Write a Dart program to convert string to sentencecase
### Description

Write a Dart program that converts a string to a sentence case.

Sentence case is a style of writing in which the first letter of the first word is capitalized, while all other letters are in lowercase. However, there are some exceptions to this rule. For example, proper nouns (such as names of people, places, organizations, etc.) and acronyms (such as NASA, FBI, etc.) should always be capitalized, regardless of their position in the sentence. The first word after a colon or a semicolon may also be capitalized.

Here is an example of a sentence in sentence case: "**The quick brown fox jumps over the lazy dog.**" In this sentence, only the first letter of the first word is capitalized, while all other letters are in lowercase. However, if the sentence contains proper nouns or acronyms, they should also be capitalized. For example: "**John and Jane went to New York to visit the Museum of Modern Art (MoMA).**" In this sentence, the first letter of the first word, as well as the proper nouns "John", "Jane", "New York", and "Museum of Modern Art", and the acronym "MoMA" are capitalized.

Here are some examples of converting strings to sentence cases:

Example 1:
```
Input: "john and jane went to new york to visit the museum of modern art (moma)"
Output: "John and Jane went to New York to visit the Museum of Modern Art (MoMA)"
```

Example 2:
```
Input: "the united nations (un) is an international organization"
Output: "The United Nations (UN) is an international organization"
```

Example 3:
```
Input: "the cat is sleeping; however, the dog is awake"
Output: "The cat is sleeping; however, the dog is awake"
```

### Hints

<details>
<summary>Hint 1:</summary>

Start by taking two inputs: the input text and a list of fixed words (e.g., proper nouns, names, acronyms). The list should contain words that should always be capitalized.

</details>

<details>
<summary>Hint 2:</summary>

Convert the entire input text to lowercase. Then, iterate through the list of fixed words and replace each occurrence in the text with its capitalized form.

</details>

<details>
<summary>Hint 3:</summary>

Check if the list of fixed words is empty. If it is, it means that all words should be treated the same way. In this case, convert the entire text to lowercase and capitalize only the first letter of the first word.

</details>

<details>
<summary>Hint 4:</summary>

Consider special cases, such as words that should always be capitalized after a colon or semicolon. Handle these cases separately to ensure correct sentence case formatting.

</details>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-sentencecase/convert_string_to_sentencecase.dart` file

</details>

### PR DESCRIPTION
**Pull request by shaurya-clemson**
## 📑 Description

Created a Dart program to replace a string with sentence case. Wrote more legible, bug-free code in place of the file already present.

## 🐞 Related Issue

Closes #3718

### CODE REVIEW

**Review by 0ME9A — CHANGES_REQUESTED** [review]
Hi @shaurya-clemson,

I appreciate your contribution to the project, but I'm afraid the program you submitted doesn't seem to address the specific requirements outlined in issue #3718. I'd be grateful if you could take another look at the issue instructions and make sure your program aligns with the specified goals. 

If you have any questions or need further clarification, please don't hesitate to ask. I'm here to help in any way I can.

**Comment by shaurya-clemson** [comment]
Hi @0ME9A 

Looks like I missed the extended description of the problem. I'll make the required changes shortly. Thanks for letting me know!

**Review by 0ME9A — APPROVED** [review]
Hi @shaurya-clemson,

Big appreciation for your stellar work on #3718! 🚀 Your solution was spot-on and made a significant impact. Your dedication to quality coding is truly valued.

Cheers,
@0ME9A

**Comment by shaurya-clemson** [comment]
@0ME9A Thank you so much for your kind words! It was a challenging problem that I really enjoyed solving. Please keep doing the good work you guys are doing :)

**Pull request merged**
