### PR TITLE
Resolved issue: Write a F# program to print diamond pattern #3543

### LINKED ISSUE #3543: [Program]: Write a F# program to print diamond pattern
### Description

Write a F# program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-diamond-pattern/program/PrintDiamondPattern.fs` file

</details>

### PR DESCRIPTION
**Pull request by anvithayerneni**
## 🐞 Related Issue

Closes #3543

### CODE REVIEW

**Comment by anvithayerneni** [comment]
@hi-Kartik2004  @isyuricunha
can you please have a look into my PR
Thanks & Regards,
Anvitha

**Review by isyuricunha — APPROVED** [review]

**Comment by isyuricunha** [comment]
looks ok to me

**Comment by anvithayerneni** [comment]
@hi-Kartik2004 
can you please have a look into my PR
Thanks & Regards,
Anvitha

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
