### PR TITLE
find_the_largest_three_elements_in_an_array.dart

### LINKED ISSUE #5170: Write a Dart program to find the largest three elements in an array
### Description

Write a Dart program to find the largest three elements in an array

```txt
Input  : arr[] = {10, 4, 3, 50, 23, 90}
Output : 90, 50, 23

Input  : arr[] = {10, 4, 3, 50, 23, 90, 1, 100, 49}
Output : 100, 90, 50
```
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/find-the-largest-three-elements-in-an-array/find_the_largest_three_elements_in_an_array.dart`
- Commit the changes
- Create a pull request

</details>

### PR DESCRIPTION
**Pull request by PunugupatiSaikumar**
find the largest three elements in an array.dart

## 🐞 Related Issue

Closes #5170

### CODE REVIEW

**Review by isyuricunha — CHANGES_REQUESTED** [review]
We have one issue.

The issue in your code lies in how the array is passed to the `selection_sort` function. When you call `selection_sort(numbers)`, the array `numbers` is passed by value, not by reference. This means that the function operates on a copy of the array, and any modifications made within the function do not affect the original array outside the function.

To fix this, you need to pass the array by reference. In Ruby, arrays are passed by reference, but the reference itself is copied. So, any modifications to the array inside the function will affect the original array.

To resolve this, you simply need to call the `selection_sort` function like this:

```ruby
selection_sort(numbers)
```

Now, when the `selection_sort` function is executed, it will directly modify the contents of the `numbers` array. After the function call, you can print the sorted array using:

```ruby
puts "Sorted array: #{numbers}"
```

This way, the sorted array will reflect the changes made inside the `selection_sort` function, and you'll see the correct result when you print it.

**Comment by isyuricunha** [comment]
> We have one issue.
> 
> The issue in your code lies in how the array is passed to the `selection_sort` function. When you call `selection_sort(numbers)`, the array `numbers` is passed by value, not by reference. This means that the function operates on a copy of the array, and any modifications made within the function do not affect the original array outside the function.
> 
> To fix this, you need to pass the array by reference. In Ruby, arrays are passed by reference, but the reference itself is copied. So, any modifications to the array inside the function will affect the original array.
> 
> To resolve this, you simply need to call the `selection_sort` function like this:
> 
> ```ruby
> selection_sort(numbers)
> ```
> 
> Now, when the `selection_sort` function is executed, it will directly modify the contents of the `numbers` array. After the function call, you can print the sorted array using:
> 
> ```ruby
> puts "Sorted array: #{numbers}"
> ```
> 
> This way, the sorted array will reflect the changes made inside the `selection_sort` function, and you'll see the correct result when you print it.

My bad. I commented on wrong PR.

Your solution works fine.

**Comment by isyuricunha** [comment]
> We have one issue.
> 
> The issue in your code lies in how the array is passed to the `selection_sort` function. When you call `selection_sort(numbers)`, the array `numbers` is passed by value, not by reference. This means that the function operates on a copy of the array, and any modifications made within the function do not affect the original array outside the function.
> 
> To fix this, you need to pass the array by reference. In Ruby, arrays are passed by reference, but the reference itself is copied. So, any modifications to the array inside the function will affect the original array.
> 
> To resolve this, you simply need to call the `selection_sort` function like this:
> 
> ```ruby
> selection_sort(numbers)
> ```
> 
> Now, when the `selection_sort` function is executed, it will directly modify the contents of the `numbers` array. After the function call, you can print the sorted array using:
> 
> ```ruby
> puts "Sorted array: #{numbers}"
> ```
> 
> This way, the sorted array will reflect the changes made inside the `selection_sort` function, and you'll see the correct result when you print it.

My bad. I commented in wrong PR.

**Review by isyuricunha — APPROVED** [review]

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
