### PR TITLE
convertStringToReversecase.scala

### PR DESCRIPTION
**Pull request by bhushanmarathe**
Program in scala to convert string to reverse case

## 📑 Description

copilot:summary

## 🐞 Related Issue

Closes ##3838

## 📋 Explanation of changes

copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
Can you please add the issue I'd to this PR

**Comment by bhushanmarathe** [comment]
@anandfresh What exactly I have to do?
I have solved the issue and submitted the file in the desired location.

**Comment by bhushanmarathe** [comment]
@anandfresh 
here is the issue
Write a Scala program to convert string to reversecase

Reversecase is a style of writing in which all lowercase letters are converted to uppercase and all uppercase letters are converted to lowercase.

Input  : "hello world"
Output : "HELLO WORLD"

**Comment by anandfresh** [comment]
> @anandfresh here is the issue Write a Scala program to convert string to reversecase
> 
> Reversecase is a style of writing in which all lowercase letters are converted to uppercase and all uppercase letters are converted to lowercase.
> 
> Input : "hello world" Output : "HELLO WORLD"

@bhushanmarathe  Please add the issue id in the PR description
example : Closes #4688

**Comment by bhushanmarathe** [comment]
@anandfresh I have updated the PR description.

**Review by anandfresh — APPROVED** [review]

**Review by RiteshK-611 — APPROVED** [review]

**Pull request merged**
