### PR TITLE
4109: Implement 90-degree Cylindrical Rotation of a Matrix in R

### LINKED ISSUE #4109: [Program]: Write a R program to cylindrically rotate a matrix by 90 degrees
### Description

Write a R program to cylindrically rotate a matrix by 90 degrees

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
7 4 1
8 5 2
9 6 3
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/cylindrically-rotate-a-matrix-by-90-degrees/cylindrically_rotate_a_matrix_by_90_degrees.r` file

</details>

### PR DESCRIPTION
**Pull request by Monika-Tiyyagura**
Title: Implement 90-degree Cylindrical Rotation of a Matrix in R

📑 ## Description

This pull request introduces a new function, cylindrical_rotate_90, in R that performs a 90-degree cylindrical rotation of a given matrix. The rotation is achieved by reversing the rows of the matrix and reassigning them as columns in a new matrix.

🐞## Related Issue
Closes https://github.com/codinasion/codinasion/issues/4109

📋 Explanation of changes
Added a new R function, cylindrical_rotate_90, that performs the required rotation.
The function takes a matrix as input and returns the matrix rotated by 90 degrees in a cylindrical manner.
copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by anandfresh — APPROVED** [review]

**Comment by Monika-Tiyyagura** [comment]
@victoriacheng15 can you please review the code and merge the PR to close this issue?

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
I checked the code with Replit online editor and the output below is what I got.

```
Input Matrix:
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

Output Matrix:
     [,1] [,2] [,3]
[1,]    3    6    9
[2,]    2    5    8
[3,]    1    4    7
```

**Comment by Monika-Tiyyagura** [comment]
> I checked the code with Replit online editor and the output below is what I got.
> 
> ```
> Input Matrix:
>      [,1] [,2] [,3]
> [1,]    1    2    3
> [2,]    4    5    6
> [3,]    7    8    9
> 
> Output Matrix:
>      [,1] [,2] [,3]
> [1,]    3    6    9
> [2,]    2    5    8
> [3,]    1    4    7
> ```

@victoriacheng15 I think its the compiler notation. The numbers in the square brackets are just the indices of rows and columns but not the actual input. correct me if I am wrong. And also made changes in the code to display correct output. Please review it and merge the PR. Thank you.

**Review by victoriacheng15 — APPROVED** [review]

**Comment by Monika-Tiyyagura** [comment]
Thanks @victoriacheng15 for approving and merging the CR.

**Pull request merged**
