### PR TITLE
[Closed] issue fixed #452

### LINKED ISSUE #452: [Program]: Write a R program to find power of a number by recursion
### Description

Write a R program to find power of a number by recursion

Power of a number is calculated by multiplying the number by itself for the given number of times. For example, 2^3 = 2 * 2 * 2 = 8.

Power of a number can be calculated by recursion. The formula is:

```math
x^n = x * x^{n-1}
```

```
Input  : 2 3
Output : 8
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-power-of-a-number-by-recursion/find_power_of_a_number_by_recursion.r` file

</details>

### PR DESCRIPTION
**Pull request by maheshmeleti**
power by recursion

## 🐞 Related Issue

Closes #452

### CODE REVIEW

**Comment by maheshmeleti** [comment]
made the required changes. please review.

**Review by anandfresh — CHANGES_REQUESTED** [review]
@maheshmeleti Please add an example to execute this R function

**Review by anandfresh — CHANGES_REQUESTED** [review]
@maheshmeleti Can you please add an example to execute this function by giving an input as shown in the issue.

**Comment by isyuricunha** [comment]
This PR will be closed, and it can be reopened if the author requests it and/or wishes to do so.

Clarification:

A change was requested in the PR, but the author did not make the modifications needed for the merge to be authorized.

**Pull request closed without merging**
