### PR TITLE
Solved : Write a Scala program to find the inverse of a #3943

### LINKED ISSUE #3943: [Program]: Write a Scala program to find the inverse of a
### Description

Write a Scala program to find the inverse of a

The inverse of a square matrix A is another square matrix B such that the product of A and B is the identity matrix I. The inverse of A is denoted as A<sup>-1</sup>.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
-0.16666666666666666 0.3333333333333333 -0.16666666666666666
0.3333333333333333 -0.6666666666666666 0.3333333333333333
-0.16666666666666666 0.3333333333333333 -0.16666666666666666
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-the-inverse-of-a/findTheInverseOfA.scala` file

</details>

### PR DESCRIPTION
**Pull request by hemu-git-hub**
## 📑 Description

copilot:summary

## 🐞 Related Issue

Closes #3943 

## 📋 Explanation of changes

copilot:walkthrough

copilot:poem

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
@hemu-git-hub please add the issue id to this PR

**Comment by isyuricunha** [comment]
@hemu-git-hub , please make sure to make the corrections mentioned, or your PR may be terminated.

**Comment by hemu-git-hub** [comment]
I will do it asap.

**Comment by hemu-git-hub** [comment]
Hi @isyuricunha @anandfresh I have made the requested changes. Can you review the changes and approve my PR. Thank you.

**Review by anandfresh — APPROVED** [review]

**Review by RiteshK-611 — APPROVED** [review]

**Pull request merged**
