### PR TITLE
Added Go program to convert time from 12-24 hour Close:-2810

### LINKED ISSUE #2810: [Program]: Write a GO program to convert time from 12-hour to 24-hour format
### Description

Write a GO program to convert time from 12-hour to 24-hour format

```
Input  : 12:05:45PM
Output : 12:05:45
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-time-from-12-hour-to-24-hour-format/program/convert_time_from_12-hour_to_24-hour_format.go` file

</details>

### PR DESCRIPTION
**Pull request by AshitaSingamsetty**
Closes #2810

### CODE REVIEW

**Comment by 0ME9A** [comment]
Hi @AshitaSingamsetty, in order to proceed to the next step, it is necessary to include the IssueId in the pull request. Please add the IssueId using the format shown below:

Closes:- #issueId

**Review by anandfresh — CHANGES_REQUESTED** [review]
Please add the issue id to this PR

**Review by 0ME9A — APPROVED** [review]
Congratulations GifGIF

**Comment by hi-Kartik2004** [comment]
> Hi @AshitaSingamsetty, in order to proceed to the next step, it is necessary to include the IssueId in the pull request. Please add the IssueId using the format shown below:
> 
> Close:- #issueId

Hi @0ME9A,
Closes:- #id does not follow the standard GitHub syntax for closing pull requests (PRs)
`Close #2719 `  or `Closes #2719`  are the right ones.

- Edited the first comment.
Thanks.

**Review by hi-Kartik2004 — APPROVED** [review]

**Review by anandfresh — APPROVED** [review]

**Pull request merged**
