### PR TITLE
[Closed] Shades of green

### PR DESCRIPTION
**Pull request by 0ME9A**
## 📑 Description
background wallpaper added.

Closes #

---

copilot:all

### CODE REVIEW

**Comment by 0ME9A** [comment]
Could you check where the errors are and why?

**Comment by harshraj8843** [comment]
Hey @0ME9A 

Thanks for this update. There are a few issues to be fixed.

Please `Allow edits by maintainers`. I will update the code owners file soon 😅

**Comment by 0ME9A** [comment]
> Hey @0ME9A
> 
> Thanks for this update. There are a few issues to be fixed.
> 
> Please `Allow edits by maintainers`. I will update the code owners file soon 😅

Done 👍

**Review by 0ME9A — COMMENTED** [review]
All reviews checked.

**Pull request closed without merging**
